# .bashrc
# Note: a lot of magic is happening in .inputrc
# Missing:
# - fancy ctrl-z
# - fancy history substring search
# - sane defaults
# - framework?
#
# TODO: Integrate features from https://github.com/barryclark/bashstrap
# ...or the updated fork, https://github.com/andystanton/bashstrap
#
# ...or migrate to Bash-It? https://github.com/Bash-it/bash-it

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# If this isn't an interactive prompt, abort:
[ -z "$PS1" ] && return

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# Env setup
export EDITOR=vim

## Prompt setup
# TODO: Use https://github.com/RichVel/nicer-bash-prompt
# This somehow prevents conda env modification from messing up PS1:
PROMPT_COMMAND="history -a; printf ''"
# Taken from: http://hocuspokus.net/2009/07/add-git-and-svn-branch-to-bash-prompt/
# Update with: https://blog.petdance.com/2013/04/24/my-bash-prompt-with-gitsvn-branchstatus-display/
parse_git_branch() {
	git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
parse_svn_branch() {
  # parse_svn_url | sed -e 's#^'"$(parse_svn_repository_root)"'##g' | awk '{print " (svn::"$1")" }'
  parse_svn_url | sed -e 's#^'"$(parse_svn_repository_root)"'##g' | awk '{print " (svn)" }'
}
parse_svn_url() {
  svn info 2>/dev/null | sed -ne 's#^URL: ##p'
}
parse_svn_repository_root() {
  svn info 2>/dev/null | sed -ne 's#^Repository Root: ##p'
}

COLOR_RED=$(tput setaf 1)
COLOR_GREEN=$(tput setaf 2)
COLOR_YELLOW=$(tput setaf 3)
COLOR_BLUE=$(tput setaf 4)
COLOR_PURPLE=$(tput setaf 5)
COLOR_OCHRE="\033[38;5;95m"
COLOR_WHITE=$(tput setaf 7)
COLOR_RESET=$(tput sgr0)
COLOR_BOLD=$(tput bold)
function git_color {
  local git_status="$(git status 2> /dev/null)"
  if [[ ! $git_status =~ "working directory clean" ]]; then
    echo -e $COLOR_RED
  elif [[ $git_status =~ "Your branch is ahead of" ]]; then
    echo -e $COLOR_YELLOW
  elif [[ $git_status =~ "nothing to commit" ]]; then
    echo -e $COLOR_GREEN
  else
    echo -e $COLOR_OCHRE
  fi
}
PS1="\[$COLOR_GREEN\]\u\[$COLOR_RESET\]@"
# TODO: possible conditional on what the hostname is
PS1+="\[$COLOR_GREEN\]\[$COLOR_BOLD\]\h: \[$COLOR_RESET\]"
PS1+="\[$COLOR_YELLOW\]\[$COLOR_BOLD\]\w\[$COLOR_RESET\]"
PS1+="\$(parse_svn_branch)"
PS1+="\[\$(git_color)\]\$(parse_git_branch)\[$COLOR_RESET\]"
PS1+="\\$ "
export PS1

## Option setup (assuming bash 4+)
shopt -s autocd
shopt -s cdspell
shopt -s checkjobs
shopt -s checkwinsize
shopt -s cmdhist
# direxpand unavailable for bash < 4.2
shopt -s direxpand 2> /dev/null
shopt -s dirspell
shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s nocaseglob
shopt -s nocasematch
shopt -s histappend

HISTFILESIZE=1000000
HISTSIZE=1000000
HISTCONTROL=ignoreboth # don't store duplicates, commands that start w/ space
HISTIGNORE='ls:bs:fg:history:clear'

## Load autocompletion
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi



# ## Try cycling through substrings
# n() {
#       mapfile -t COMPREPLY < <(ls -d */ | grep "${COMP_WORDS[COMP_CWORD]}")
# }
# complete -F _cd_completion cd

if [ -f ~/dotfiles/shell/aliases.sh ]; then
	. ~/dotfiles/shell/aliases.sh
fi
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi
# TODO: define dotfile home with -z $SSHHOME
if [ ! -z "$SSHHOME" ] && [ -f $SSHHOME/.sshrc.d/shell/aliases.sh ]; then
  . $SSHHOME/.sshrc.d/shell/aliases.sh
fi
if [ ! -z "$SSHHOME" ]; then
  export GIT_PAGER=less
fi
## Load autojump
if [ -f /usr/share/autojump/autojump.sh ]; then
	. /usr/share/autojump/autojump.sh
fi

## Load FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

## Modify common commands
function cd {
	builtin cd "$@" && ls -F --color=always
}
if [ -x /usr/bin/dircolors ]; then
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

## Local adjustments
if [ -f ~/.bashrc_local ]; then
	. ~/.bashrc_local
fi
module load miniconda >/dev/null 2>&1

## Disable ctrl-s (freezes the terminal, resumption with ctrl-q)
# Credit: https://unix.stackexchange.com/a/332793
stty -ixon
