#!/bin/bash
if [ ! -z "$SSHHOME" ]; then
  DOTHOME="$SSHHOME/.sshrc.d"
elif [ ! -z "$SHHOME" ]; then
  DOTHOME="$SHHOME/.dockershrc.d"
fi

if [ ! -z "$DOTHOME" ]; then
  source $DOTHOME/shell/bashrc
  export INPUTRC=$DOTHOME/shell/inputrc
  export VIMINIT="let \$MYVIMRC='$DOTHOME/vimrc_minimal' | source \$MYVIMRC"
fi

# if [ -z "~/.gitconfig" ]; then
#   if [ $(hostname | grep ncanda | wc -l) != 1 ]; then
#     cp $DOTHOME/shell/gitconfig ~/.gitconfig
#   fi
# fi
