## Essentials
brew "git"
brew "hub"
brew "tmux"
brew "reattach-to-user-namespace"
brew "mercurial"
brew "python3"
brew "ruby"
brew "rbenv"
brew "rbenv-ctags"

tap "homebrew/science"
brew "R"

## Better CLI
brew "autojump"
brew "zsh"
brew "zsh-completions"
# brew "z"
brew "watch"
brew "colordiff"
brew "automake"
brew "autoconf"
# brew "mosh"
brew "coreutils"
brew "findutils"
brew "osxutils"

### Completions
brew "brew-cask-completion"
brew "bundler-completion"
brew "gem-completion"
brew "ruby-completion"
brew "rake-completion"
brew "rails-completion"
brew "pip-completion"
brew "launchctl-completion"
brew "docker-completion"
brew "docker-compose-completion"
brew "vagrant-completion"

## Tools
### General / Misc
brew "wget"
brew "curl"
brew "googler"
brew "dos2unix"
brew "ssh-copy-id"
brew "ossp-uuid"
brew "pidof"
brew "htop"
brew "pandoc"
brew "pandoc-crossref"
brew "pandoc-citeproc"
brew "heroku-toolbelt"

# brew "cadaver"
# brew "editorconfig"
# brew "fdups"
# brew "openssl"
# brew "openvpn"

## Better vim
brew "ack"
brew "the_silver_searcher"
brew "fzf"
brew "vim"
brew "ctags"
brew "cscope"

### Mutt
tap "kevwil/patches"
brew "kevwil/patches/mutt" # with trash patch
brew "abook"
brew "lbdb"
brew "isync"
brew "notmuch"
brew "urlview"

### Image tools
brew "ghostscript"
brew "imagemagick"
