# .bashrc
# Missing:
# - aliases
# - fancy ctrl-z
# - up-arrow-delimited history search / other fancy history substring search
# - git-status in PS1
# - auto-ls / auto-gst
# - sane defaults
# - framework?

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export EDITOR=vim
export PS1="\[\033[35m\]\t\[\033[m\] \[\033[36m\]\u\[\033[m\]@\[\033[36m\]\h: \[\033[33;1m\]\w\[\033[m\]\$ "

# Assuming bash 4+
shopt -s autocd
shopt -s cdspell
shopt -s checkjobs
shopt -s cmdhist
shopt -s direxpand
shopt -s dirspell
shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s nocaseglob
shopt -s nocasematch

alias l="ls -la --color=always"
alias interactive="srun --pty -p interactive -c 1 -t 01:00:00 --mem-per-cpu=4096 bash"
